feign:
  client:
    url:
      fhirServer: ${FHIR_SERVER_URL:https://fhir.qa.cqgc.hsj.rtss.qc.ca/fhir}
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
security:
  enabled: ${SECURITY_ENABLED:true}
  audience: ${SECURITY_AUDIENCE:clin-acl}
  issuer: ${SECURITY_ISSUER:https://auth.qa.cqgc.hsj.rtss.qc.ca/auth/realms/clin}
  cors:
    - "http://localhost:2000"
    - "https://qa.cqgc.hsj.rtss.qc.ca"
    - "https://staging.cqgc.hsj.rtss.qc.ca"
    - "https://cqgc.hsj.rtss.qc.ca"