feign:
  client:
    url:
      fhirServer: ${FHIR_SERVER_URL:https://fhir.qa.clin.ferlab.bio/fhir}
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
security:
  enabled: ${SECURITY_ENABLED:true}
  audience: ${SECURITY_AUDIENCE:clin-acl}
  issuer: ${SECURITY_ISSUER:https://auth.qa.clin.ferlab.bio/auth/realms/clin}
  cors:
    - "http://localhost:2000"
    - "https://qa.clin.ferlab.bio"
    - "https://staging.clin.ferlab.bio"
    - "https://clin.ferlab.bio"