feign:
  client:
    url:
      fhirServer: ${FHIR_SERVER_URL:http://localhost:8080/fhir/}
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
security:
  enabled: ${SECURITY_ENABLED:true}
  audience: ${SECURITY_AUDIENCE:account}
  issuer: ${SECURITY_ISSUER:http://localhost:8081/auth/realms/master}
  cors:
    - "http://localhost:2000"
    - "https://qa.clin.ferlab.bio"
    - "https://staging.clin.ferlab.bio"
    - "https://clin.ferlab.bio"